name: "Test Extractor"
description: >-
  Extract test results, coverage results, code quality
  results and metadata to be piped to other CI steps
author: "kirinnee"
inputs:
  name:
    required: true
    description: "Name and unique identifier of this report"
  url:
    required: true
    description: "URL to the actual report"
  type:
    required: true
    description: "Type of report. Accepts 'vitest-result' and 'vitest-istanbul-coverage'"
  path:
    required: true
    description: "Path to find the report metadata"
runs:
  using: "node16"
  main: "dist/index.js"
