name: "Setup CloudFlare Pages"
on:
  workflow_dispatch:
env:
  ENABLE_PNPM_CACHE: "false"
  SETUP_COMPLETE: "false"
jobs:
  SetupCloudflare:
    name: Setup CloudFlare Pages
    runs-on:
      - nix
      - ARM64
    steps:
      - name: Gotrade CI Environment
        uses: kirinnee/atomici-action@v2.3.1

      - name: Checkout Code
        uses: actions/checkout@v3
        with:
          fetch-depth: 0

      - name: Create CloudFlare Pages
        env:
          DOMAIN: tr8.wiki
          CF_SUB: action
          CF_TOKEN: ${{ secrets.CLOUDFLARE_API_TOKEN }}
          CF_ACCOUNT_ID: ${{ secrets.CLOUDFLARE_ACCOUNT_ID }}
          CF_ZONE: ${{ secrets.CLOUDFLARE_ZONE_ID }}
          CF_WARP_ID: ${{ secrets.CLOUDFLARE_WARP_ID }}
          CF_OKTA_ID: ${{ secrets.CLOUDFLARE_OKTA_ID }}
          NON_INTERACTIVE: "1"
          NIXPKGS_ALLOW_UNFREE: "1"
          DEBUG: "1"
        run: nix-shell nix/shells.nix -A ci --run scripts/ci/setup-cloudflare.sh
      - name: Commit Changes
        uses: EndBug/add-and-commit@v9
        with:
          add: .github/workflows/cicd.yml
