name: "Setup CloudFlare Pages"
on:
  workflow_dispatch:
env:
  ENABLE_PNPM_CACHE: "false"
  SETUP_COMPLETE: "false"
jobs:
  SetupCloudflare:
    name: Setup CloudFlare Pages
    runs-on:
      - nix
      - ARM64
    steps:
      - name: Checkout Code
        uses: actions/checkout@v3
        with:
          fetch-depth: 0

      - name: Create CloudFlare Pages
        env:
          DOMAIN: tr8.wiki
          CF_SUB: action
          CF_TOKEN: ${{ secrets.CLOUDFLARE_API_TOKEN }}
          CF_ACCOUNT_ID: ${{ secrets.CLOUDFLARE_ACCOUNT_ID }}
          CF_ZONE: ${{ secrets.CLOUDFLARE_ZONE_ID }}
          CF_WARP_ID: ${{ secrets.CLOUDFLARE_WARP_ID }}
          CF_OKTA_ID: ${{ secrets.CLOUDFLARE_OKTA_ID }}
          NON_INTERACTIVE: "1"
        run: |
          ./scripts/ci/setup-cloudflare-single.sh "${{ github.repository }}" "Unit Test" "Test Report"
          ./scripts/ci/setup-cloudflare-single.sh "${{ github.repository }}" "Unit Test" "Coverage Report"
          ./scripts/ci/setup-cloudflare-single.sh "${{ github.repository }}" "Integration Test" "Test Report"
          ./scripts/ci/setup-cloudflare-single.sh "${{ github.repository }}" "Integration Test" "Coverage Report"
          gomplate -d config=./repo.yaml -f ./.github/workflows/cicd.yml --left-delim "{{{" --right-delim "}}}" -o ./.github/workflows/cicd.yml
          rm repo.yaml
      - name: Commit Changes
        uses: EndBug/add-and-commit@v9
        with:
          add: .github/workflows/cicd.yml
